name: Push-to-EC2

on: push  
      branches: [ master ]
  

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: install dependencies ##check name
        run: npm install
      - name: create production build
        run: npm run build  
    
    

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./" ##build/##multiplejobs/multipleenv
          REMOTE_HOST: "ec2-18-116-117-17.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/tmp/react-js-sample/"
      

